
#[derive(Debug)]
pub enum TokenType {
    Head1, // "# "
    Head2, // "## "
    Head3, // "### "
    Head4, // "#### "
    Head5, // "##### "
    List, // "- " | "+ " | "* "
    Order, // "1. " .. "9. "
    CodeInline, // "`"
    CodeBlock, // "```"
    TableStart, // "|--|"
    TableHead, // "--|"
    TableContents, // "|"
    LinkExpStart, // "["
    LinkExpEnd, // "]"
    LinkURLStart, // "("
    LinkURLEnd, // ")"
    ImageAltStart, // "!["
    ImagaAltEnd, // "]"
    ImageURLStart, // "("
    ImageURLEnd, // ")"
    Quote, // ">"
    Bold, // "--" | "**" | "++"
    Italic, // "-" | "*" | "+"
    Strikethrough, // "~~"
    Line, // "---" | "***" | "+++"
}